import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from './_myComponants/Navbar/Navbar';
import { SessionProvider } from 'next-auth/react';
import SessionProviderServer from "./_myComponants/SessionProviderServer/SessionProviderServer";
import { Toaster } from "sonner";
import CartContext from "./_context/cartContext";
import { getUserCart } from "@/services/getUserCart";
import  Wishlistcontext  from "./_context/wishlistContext";
import { getUsetWishlist } from "@/services/getUserWishlist";
import Footer from "./_myComponants/Footer/Footer";
import { getAllBrands } from "@/services/brands.services";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  

}>) {
  const cartUser = await getUserCart()
  const WishlistUser =await  getUsetWishlist()
  
  
  
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Wishlistcontext WishlistUser={WishlistUser}>
       <CartContext cartUser={cartUser}>
         <SessionProviderServer>
          <Toaster/>
          <Navbar/>
          {children}
          <Footer></Footer>
        </SessionProviderServer>
       </CartContext>
       </Wishlistcontext>
       
      </body>
    </html>
  );
}
